install:
  - where nuget
  - choco install gitversion.portable -pre -y
  - where nuget

before_build:
  - nuget.exe restore NHtmlUnit.sln -verbosity detailed
  - ps: gitversion /l console /output buildserver

build:
  project: NHtmlUnit.sln

test:
  assemblies:
    - 'tests/**/bin/*/*Tests.dll'
